language: julia
julia:
 - 1.5.1

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
    - stage: "Tests"

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
